### ISSUE TITLE
Data streams shouldn't be opened when redeploying devices

### ISSUE THREAD

**Issue by Whathecode** [imotions/carp.core-kotlin#383]
There may be a bug when devices are redeployed (currently not thoroughly tested yet). When devices are deployed and a deployment is "Running" for the first time, the necessary data streams are opened in the data subsystem.

However, this call still occurs when devices are redeployed (after an unregister and register call), which will likely result in a 500 error when `DeviceDeployed` is called.

**Comment by ltj** [comment]
Can this be solved by simply making the open call idempotent?
